BEGIN;
REVOKE ALL ON TABLE public."TblP127Editor" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127Place" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127Route" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127Journey" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127Post" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127PostTranslation" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127PostPlace" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127PostRoute" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127Media" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127MediaTranslation" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP127Reaction" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public."P127IsEditor"() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127IsEditor"() TO anon, authenticated;
REVOKE ALL ON FUNCTION public."P127MediaReadable"(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127MediaReadable"(text) TO anon, authenticated;
REVOKE ALL ON FUNCTION public."P127GetContent"(boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127GetContent"(boolean) TO anon, authenticated;
REVOKE ALL ON FUNCTION public."P127SavePost"(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127SavePost"(jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public."P127SaveCatalog"(text,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127SaveCatalog"(text,jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public."P127RegisterMedia"(uuid,text,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127RegisterMedia"(uuid,text,text) TO authenticated;
REVOKE ALL ON FUNCTION public."P127SaveMedia"(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127SaveMedia"(jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public."P127ForgetMedia"(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127ForgetMedia"(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public."P127Thank"(uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P127Thank"(uuid,uuid) TO anon, authenticated;
COMMIT;
